#!/bin/bash
#### Script to generate file sar ######
#Alfa Version 0.1
##Add the sysstat version from your local environment
sysstat1="sysstat-7.0.2-3.el5_5.1.x86_64";
sysstat2="sysstat-9.0.4-27.el6.x86_64";
sysstat3="sysstat-7.0.2-11.el5.x86_64";
sysstat4="sysstat-9.0.4-12.el6_0.1.x86_64";
sysstat5="sysstat-9.0.4-22.el6.x86_64";
sysstat6="sysstat-10.1.5-11.el7.x86_64";

#Edit parameter according to your needs example {01..28} or {02..30}
for t in {01..27}; do 
   #Checking Version Of Sysstat In Sosreport File
   CHECK="$(cat $t/installed-rpms | grep syss | awk '{print $1}')";
	
  #After checking then create sar file from sa file in sosreport
  if [ "$CHECK" == "$sysstat1" ] 
	then
		for day in {01..31}; do
		#checking directory for new sar file
		directory="newsarfile"
		if [ ! -d "$t/var/log/sa/$directory" ] ; then
		mkdir $t/var/log/sa/$directory
		fi
		#generating new sar file
		##Change the location of the sysstat directory is located in your local machine
		 LC_ALL=C ../../../sysstat/sysstat-7.0.2-3.el5.x86_64/usr/bin/sar -A -f $t/var/log/sa/sa$day > $t/var/log/sa/$directory/sar$day
		#generating merge sar file
		##Change the location of the sysstat directory is located in your local machine
		LC_ALL=C ../../../sysstat/sysstat-7.0.2-3.el5.x86_64/usr/bin/sar/usr/bin/sar -A -f $t/var/log/sa/sa$day >> $t/var/log/sa/$directory/sarMerge	
		
		done
	elif [ "$CHECK" == "$sysstat2" ]
	then
		for day in {01..31}; do
		#checking directory for new sar file
		directory="newsarfile"
		if [ ! -d "$t/var/log/sa/$directory" ] ; then
		mkdir $t/var/log/sa/$directory
		fi
		#generating new sar file
		##Change the location of the sysstat directory is located in your local machine
		 LC_ALL=C ../../../sysstat/sysstat-9.0.4-27.el6.x86_64/usr/bin/sar -A -f $t/var/log/sa/sa$day > $t/var/log/sa/$directory/sar$day
		#generating merge sar file
		##Change the location of the sysstat directory is located in your local machine
		LC_ALL=C ../../../sysstat/sysstat-9.0.4-27.el6.x86_64/usr/bin/sar/usr/bin/sar -A -f $t/var/log/sa/sa$day >> $t/var/log/sa/$directory/sarMerge

		done
	elif [ "$CHECK" == "$sysstat3" ]
	then	
		for day in {01..31}; do
		#checking directory for new sar file
		directory="newsarfile"
		if [ ! -d "$t/var/log/sa/$directory" ] ; then
		mkdir $t/var/log/sa/$directory
		fi
		#generating new sar file
		##Change the location of the sysstat directory is located in your local machine
		 LC_ALL=C ../../../sysstat/sysstat-7.0.2-11.el5.x86_64/usr/bin/sar -A -f $t/var/log/sa/sa$day > $t/var/log/sa/$directory/sar$day
		#generating merge sar file 
		##Change the location of the sysstat directory is located in your local machine
		LC_ALL=C ../../../sysstat/sysstat-7.0.2-11.el5.x86_64/usr/bin/sar/usr/bin/sar -A -f $t/var/log/sa/sa$day >> $t/var/log/sa/$directory/sarMerge

		done
	elif [ "$CHECK" == "$sysstat4" ]
	then	
		for day in {01..31}; do
		#checking directory for new sar file
		directory="newsarfile"
		if [ ! -d "$t/var/log/sa/$directory" ] ; then
		mkdir $t/var/log/sa/$directory
		fi
		#generating new sar file
		##Change the location of the sysstat directory is located in your local machine
		 LC_ALL=C ../../../sysstat/sysstat-9.0.4-12.el6_0.1.x86_64/usr/bin/sar -A -f $t/var/log/sa/sa$day > $t/var/log/sa/$directory/sar$day
		#generating merge sar file 
		##Change the location of the sysstat directory is located in your local machine
		LC_ALL=C ../../../sysstat/sysstat-9.0.4-12.el6_0.1.x86_64/usr/bin/sar/usr/bin/sar -A -f $t/var/log/sa/sa$day >> $t/var/log/sa/$directory/sarMerge

		done
	elif [ "$CHECK" == "$sysstat5" ]
	then	
		for day in {01..31}; do
		#checking directory for new sar file
		directory="newsarfile"
		if [ ! -d "$t/var/log/sa/$directory" ] ; then
		mkdir $t/var/log/sa/$directory
		fi
		#generating new sar file
		##Change the location of the sysstat directory is located in your local machine
		 LC_ALL=C ../../../sysstat/sysstat-9.0.4-22.el6.x86_64/usr/bin/sar -A -f $t/var/log/sa/sa$day > $t/var/log/sa/$directory/sar$day
		#generating merge sar file 
		##Change the location of the sysstat directory is located in your local machine
		LC_ALL=C ../../../sysstat/sysstat-9.0.4-22.el6.x86_64/usr/bin/sar/usr/bin/sar -A -f $t/var/log/sa/sa$day >> $t/var/log/sa/$directory/sarMerge
		
		done
	elif [ "$CHECK" == "$sysstat6" ]
	then	
		for day in {01..31}; do
		#checking directory for new sar file
		directory="newsarfile"
		if [ ! -d "$t/var/log/sa/$directory" ] ; then
		mkdir $t/var/log/sa/$directory
		fi
		#generating new sar file
		##Change the location of the sysstat directory is located in your local machine
		 LC_ALL=C ../../../sysstat/sysstat-10.1.5-11.el7.x86_64/usr/bin/sar -A -f $t/var/log/sa/sa$day > $t/var/log/sa/$directory/sar$day
		#generating merge sar file 
		##Change the location of the sysstat directory is located in your local machine
		LC_ALL=C ../../../sysstat/sysstat-10.1.5-11.el7.x86_64/usr/bin/sar/usr/bin/sar -A -f $t/var/log/sa/sa$day >> $t/var/log/sa/$directory/sarMerge
		
		done	
	else
		echo 'Wrong'
	fi
done
